services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: next_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: tail -f /dev/null
    networks:
      - timetable_network

networks:
  timetable_network:
    driver: bridge